# Generated by Django 3.1 on 2020-08-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessionConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_size', models.CharField(max_length=10)),
                ('cell_size', models.IntegerField()),
                ('ruleset_name', models.CharField(max_length=50)),
                ('aging', models.BooleanField()),
                ('processing_mode', models.IntegerField()),
                ('show_colors', models.BooleanField()),
                ('seed_image_path', models.FilePathField()),
            ],
        ),
    ]
