# Generated by Django 3.1 on 2020-08-29 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caconsole', '0002_auto_20200827_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionconfiguration',
            name='name',
            field=models.CharField(default='default name', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sessionconfiguration',
            name='processing_mode',
            field=models.IntegerField(choices=[(1, 'CPU'), (2, 'GPU')]),
        ),
    ]
